// This information will be moved to a server database. 

export default [
    {
        id:"1",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardAltText:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/uwaterloo-vertical.png"),
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon"],
    },
    {
        id:"2",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardAltText:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/unb.png"),
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon"],
    },
    {
        id:"3",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardAltText:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/aafc_logo.png"),
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon"],
    },
    {
        id:"4",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardAltText:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/data_analysis.png"),
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon"],
    },
    {
        id:"5",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardAltText:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/formula1.png"),
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon"],
    },
    {
        id:"6",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/sustainability.png"),
        cardAltText:"Coming Soon",
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon",
        ],
    },
    {
        id:"7",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/sustainability.png"),
        cardAltText:"Coming Soon",
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon",
        ],
    },
    {
        id:"8",
        title:"Coming Soon",
        cardTitle:"Coming Soon",
        cardImgURL:require("../img/company-logos/uwaterloo/sustainability.png"),
        cardAltText:"Coming Soon",
        cardCategory:"Coming Soon",
        cardDesc:"",
        dialogTitle:"Coming Soon",
        dialogSubtitle:"Coming Soon",
        dialogLocation:"Coming Soon",
        dialogYears:"Coming Soon",
        dialogContent: ["Coming Soon",
        ],
    },
]