// This information will be moved to a server database. 

export default [
    {
        id:"1",
        title:"Land Suitability Rating System",
        cardTitle:"Agriculture and Agri-Food Canada",
        cardCategory:"Full Stack Developer",
        cardDesc:"",
        dialogTitle:"Agriculture and Agri-Food Canada",
        dialogSubtitle:"Full Stack Developer // Soil Information Specialist",
        dialogLocation:"Ottawa, ON",
        dialogYears:"2020 - Present",
        dialogContent: ["Land Suitability Rating System:",
            "● Modelled complex interactions between land use and land suitability leveraging modern JavaScript, React JS, and Machine learning techniques.",
            "● Developed user interfaces with modern JavaScript (ES6+), React JS, HTML5, CSS3, Materials-UI",
            "● Leveraged MongoBD, Node.js, and REST API for back-end API calls",
            "● Implemented R and Python for machine learning in the back-end to streamline dataflow processes",
            "● Used GitHub for versioning control and multi-user level access to data",
            "● Contributed expertise in the development of products through the software lifecycle, from requirements definition through stakeholder engagements",
            "● Facilitated customization of systems by encouraging the adoptions of open source, and emerging standard for software application development",
            "● Organized large qualitative and quantitative datasets from 6 government sources, and Google Earth Engine, to further enable scientific research on millions of data points.",
            "● Implemented the Open Government Licence – Canada standards for openness, data security, and data consistency.",
            "● Reports and technical how-to documents were produced for future use",
            "Data Discovery Portal:",
            "● Lead the development of a new user interface, (developed in JS, CSS, HTML, React, and MUI), for the easy dissemination of geospatially derived data",
            "● Mentored a team of 3 developers for the successful creation of a web map portal using Geoserver, Leaflet and Google Earth Engine",
            "● Implemented an automatic reporting system for access to scientific data",
            "● Lead and planned stakeholder meetings to receive customers feedback to improve the style, look, and feel of the user experience",
            "Other Skills Enhanced:",
            "● Researched and prepared project proposals to attract $500k+ in future project funding",
            "● Co-lead the procurement and purchasing of $100k+ research equipment",
            "● Developed specifications criteria, put out a call for bids, and reviewed all tenders, awarding the call to the successful bid",
            "● Hired 10+ staff and cooperative learning students from initial job creation to final offer presentation",
            "More coming soon..."
        ],
    },
    {
        id:"2",
        title:"Land Suitability Rating System",
        cardTitle:"Town of Florenceville-Bristol",
        cardCategory:"Independent Consultant",
        cardDesc:"",
        dialogTitle:"Independent Consultant",
        dialogSubtitle:"Project Manager",
        dialogLocation:"Florenceville-Bristol, NB",
        dialogYears:"2019 - 2020",
        dialogContent: ["Environmental Action Plan Project Manager:",
            "● I developed and led a project proposal to create a climate action plan for the Town of Florenceville-Bristol, NB. This project proposal was successfully approved for $15,000.",
            "● I managed a team of 2 where we carried out an assessment on avenues to reduce greenhouse gas emissions in the local community.",
            "● I held community engagements to receive stakeholder perspective and feedback on the proposed changes and actions.",
            "● Prototyping necessary interfaces and software was critical for the successful tracking of GHG emissions. A final report was produced, with recommendations for the local action plan for the Town of Florenceville-Bristol. The town planned for a reduction of 21% of 2017 CO2 emissions by 2027.",
            "Community Environmental Program Development Manager:",
            "● I was tasked to continue working with the Town to investigate and research potential programs available to the local community for decreasing greenhouse gas emissions.",
            "● I acted as the expert, being the contact person, tasked to disseminate information to the public through reports, presentations, and direct question and answering.",
            "● This plan is be used by the public, local businesses, and government to explore potential community engagements and funding sources to increase sustainability.",
            "Key Skills Enhanced:",
            "● Lead the development of a successful contract bid and proposal ",
            "● Acted as the contact between stakeholders, community members and industry partners ",
            "● Lead workshops and community stakeholder engagements to inform and receive feedback about the proposed environmental action plan",
            "More coming soon..."
        ],
    },
    {
        id:"3",
        title:"Land Suitability Rating System",
        cardTitle:"University of Guelph",
        cardCategory:"Researcher",
        cardDesc:"",
        dialogTitle:"University of Guelph",
        dialogSubtitle:"GIS Researcher",
        dialogLocation:"Guelph, ON",
        dialogYears:"2017 - 2018",
        dialogContent: [
            "● I researched, investigated, and compared the effects of using UAVSAR data versus RADARSAT-2 data for upscaling techniques over farms in Manitoba.",
            "● the research is being used to increase productivity across farm fields in Canada by 37%.",
            "More coming soon..."
        ],
    },
    {
        id:"4",
        title:"Land Suitability Rating System",
        cardTitle:"Agriculture and Agri-Food Canada",
        cardCategory:"GIS and Remote Sensing Technician",
        cardDesc:"",
        dialogTitle:"Agriculture and Agri-Food Canada",
        dialogSubtitle:"GIS and Remote Sensing Technician",
        dialogLocation:"Ottawa, ON",
        dialogYears:"2016 - 2017",
        dialogContent: [
            "● I was tasked with assisting in researching new methods to measure changes in field soil moisture values.",
            "● I used ESRI’s ArcGIS software to edit, process and maintain databases for NASA’ SMAP satellite.",
            "● I  received and AAFC-AAC Instant award for partnerships between multiple divers industrial and academic intuitions.",
            "Key Skills Enhanced:",
            "● I was part of an 18-day validation field campaign, aiding in collecting, training, and organizing the use of scientific monitoring devices.",
            "● Expert knowledge was leveraged for the optimizations of route planning.",
            "More coming soon..."
        ],
    },
]